### Packages

In [64]:
# Load some usual packages
import numpy as np
import pandas as pd
import plotly.graph_objects as go

### Lists

In [65]:
# This is a list of numbers assigned to a variable x
x = [1,2,3,4]
x

[1, 2, 3, 4]

In [66]:
# This is a list of strings assigned to a variable y
y = ['a','b','c','d']
y

['a', 'b', 'c', 'd']

In [67]:
# pull the 1st element of the list x
x[0]

1

In [68]:
# pull the 3rd element of the list x
x[2]

3

In [69]:
# pull the 4th element of the list y
y[3]


'd'

### Numpy arrays

In [70]:
np_x = np.array(x)
np_x

array([1, 2, 3, 4])

In [71]:
np_x[0]

1

In [72]:
np_x.tolist()

[1, 2, 3, 4]

In [73]:
np.arange(1,10,1)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [74]:
np.arange(0,10,1)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [75]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### Dicts

In [76]:
new_dict = {'a': 1, 'b': 2, 'c': 3}
new_dict

{'a': 1, 'b': 2, 'c': 3}

In [77]:
new_dict['a']

1

In [78]:
new_dict.keys()
new_dict.values()

dict_values([1, 2, 3])

### Pandas DataFrames

In [79]:
df = pd.DataFrame(dtype=float,
            columns = ['Column A','Column B'] ,
            index = np.arange(5)
            )
df

Column A  Column B
0       NaN       NaN
1       NaN       NaN
2       NaN       NaN
3       NaN       NaN
4       NaN       NaN

In [80]:
df.index

Int64Index([0, 1, 2, 3, 4], dtype='int64')

In [81]:
df.columns

Index(['Column A', 'Column B'], dtype='object')

In [82]:
# Make some existing data
x = np.array([1, 2, 2, 4, 3, 6, 4, 8, 5, 10])
x = x.reshape([5,2])

# Assign it to a dataframe
df = pd.DataFrame(x, 
            columns=['Column A','ColumnB'],
            index = np.arange(5))
df

Column A  ColumnB
0         1        2
1         2        4
2         3        6
3         4        8
4         5       10

In [83]:
df['Column A']
# df.ColumnB

0    1
1    2
2    3
3    4
4    5
Name: Column A, dtype: int32

In [84]:
# acessing a row
df.loc[4]

Column A     5
ColumnB     10
Name: 4, dtype: int32

In [85]:
df.loc[4,'ColumnB']

10

In [86]:
df[df.ColumnB >= 4]

Column A  ColumnB
1         2        4
2         3        6
3         4        8
4         5       10

In [87]:
df[(df.ColumnB >= 4 ) & (df['Column A'] <=2 )]

Column A  ColumnB
1         2        4

In [88]:
df[(df.ColumnB >= 4 ) | (df['Column A'] >=2 )]

Column A  ColumnB
1         2        4
2         3        6
3         4        8
4         5       10

### Functions

In [89]:
def discount_factor(rate,num_periods):
    '''
    rate: a discount rate input in decimal notation
    num_periods: how many periods to discoun
    '''
    factor = 1/((1+rate)**num_periods)
    return factor

In [90]:
discount_factor(0.025,5)

0.8838542876095173

### Loops

In [91]:
loop_list = [5, 10, 20]
for t in loop_list:
    print(discount_factor(0.025, t))

0.8838542876095173
0.7811984017257273
0.6102709428588309


In [92]:
# Enumerate
loop_list = [5, 10, 20]
for i, t in enumerate(loop_list):
    print(i)
    print(discount_factor(0.025, t))

0
0.8838542876095173
1
0.7811984017257273
2
0.6102709428588309


In [93]:
# using a loop to create a list
x = [1 / ((1.025)**t) for t in loop_list]
x

[0.8838542876095173, 0.7811984017257273, 0.6102709428588309]

### Plots

In [94]:
fig = go.Figure()
trace = go.Scatter(x = df['Column A'], y = df['ColumnB'])
fig.add_trace(trace)
fig.show()

In [95]:
fig = go.Figure()
# plot line connecting data points
trace0 = go.Scatter(
    x = df['Column A'], 
    y = df['ColumnB'],
    mode='lines',
    name='with lines')
fig.add_trace(trace0)
# plot data markers
trace1 = go.Scatter(
    x = df['Column A'], 
    y = df['ColumnB'],
    mode='markers',
    name='with markers')
fig.add_trace(trace1)
fig.show()