# Bond markets

In [102]:
import pandas as pd
import numpy as np
from pandas_datareader import DataReader as pdr
import plotly.graph_objects as go

## Term structure from FRED

In [226]:
tseries = ['DGS'+x for x in ['1MO','3MO','1','2','3','5','10','20','30']]
df = pdr(tseries, "fred", start="1929-12-01")
df

DGS1MO  DGS3MO  DGS1  DGS2  DGS3  DGS5  DGS10  DGS20  DGS30
DATE                                                                   
1962-01-02     NaN     NaN  3.22   NaN  3.70  3.88   4.06   4.07    NaN
1962-01-03     NaN     NaN  3.24   NaN  3.70  3.87   4.03   4.07    NaN
1962-01-04     NaN     NaN  3.24   NaN  3.69  3.86   3.99   4.06    NaN
1962-01-05     NaN     NaN  3.26   NaN  3.71  3.89   4.02   4.07    NaN
1962-01-08     NaN     NaN  3.31   NaN  3.71  3.91   4.03   4.08    NaN
...            ...     ...   ...   ...   ...   ...    ...    ...    ...
2022-12-01    4.04    4.33  4.66  4.25  3.98  3.68   3.53   3.85   3.64
2022-12-02    3.91    4.34  4.69  4.28  3.99  3.67   3.51   3.79   3.56
2022-12-05    3.93    4.36  4.77  4.41  4.13  3.80   3.60   3.84   3.62
2022-12-06    3.87    4.37  4.73  4.34  4.07  3.73   3.51   3.77   3.52
2022-12-07    3.79    4.29  4.67  4.26  3.97  3.62   3.42   3.66   3.42

[15897 rows x 9 columns]

In [62]:
# Convert to monthly
df = df.reset_index()
df['month'] = df.DATE.dt.to_period('M')
df = df.groupby('month').last()
df

DATE  DGS1MO  DGS3MO  DGS1  DGS2  DGS3  DGS5  DGS10  DGS20  \
month                                                                      
1962-01 1962-01-31     NaN     NaN  3.29   NaN  3.81  3.99   4.10   4.13   
1962-02 1962-02-28     NaN     NaN  3.21   NaN  3.53  3.77   4.00   4.10   
1962-03 1962-03-30     NaN     NaN  2.97   NaN  3.39  3.61   3.86   3.98   
1962-04 1962-04-30     NaN     NaN  3.07   NaN  3.47  3.64   3.86   3.91   
1962-05 1962-05-31     NaN     NaN  2.99   NaN  3.36  3.66   3.90   3.94   
...            ...     ...     ...   ...   ...   ...   ...    ...    ...   
2022-08 2022-08-31    2.40    2.96  3.50  3.45  3.46  3.30   3.15   3.53   
2022-09 2022-09-30    2.79    3.33  4.05  4.22  4.25  4.06   3.83   4.08   
2022-10 2022-10-31    3.73    4.22  4.66  4.51  4.45  4.27   4.10   4.44   
2022-11 2022-11-30    4.07    4.37  4.74  4.38  4.13  3.82   3.68   4.00   
2022-12 2022-12-06    3.87    4.37  4.73  4.34  4.07  3.73   3.51   3.77   

         DGS30  
month           
1962-01    NaN  
1962-02    NaN  
1962-03    NaN  
1962-04    NaN  
1962-05    NaN  
...        ...  
2022-08   3.27  
2022-09   3.79  
2022-10   4.22  
2022-11   3.80  
2022-12   3.52  

[732 rows x 10 columns]

In [64]:
# Two ways to filter on a period index
# df.loc['2000']

df.loc['1992-10']


DATE      1992-10-30 00:00:00
DGS1MO                    NaN
DGS3MO                   3.03
DGS1                     3.54
DGS2                      4.4
DGS3                     4.98
DGS5                      5.9
DGS10                     6.8
DGS20                     NaN
DGS30                    7.63
Name: 1992-10, dtype: object

In [97]:
ttms = [0.0833, 0.25, 1, 2, 3, 5, 10, 20, 30]
months = ['1983-07', '1992-10', '2000-08', '2020-02', ]
yields = df.loc[months[1], tseries]
yields.index = ttms
yields=yields.dropna()
yields

0.25     3.03
1.00     3.54
2.00      4.4
3.00     4.98
5.00      5.9
10.00     6.8
30.00    7.63
Name: 1992-10, dtype: object

In [101]:
fig = go.Figure()
for m in months:
    yields = df.loc[m, tseries]
    yields.index = ttms
    yields=yields.dropna()
    
    trace= go.Scatter(
                    x=yields.index, 
                    y=yields, 
                    hovertemplate="<br>" + str(m) +"<br>%{x:.2f} year bond <br>%{y:.1f}%<extra></extra>",
                    mode="lines+markers", 
                    name=m)
    fig.add_trace(trace)
fig.update_yaxes(title='Yield (%)',tickformat=".0f")
fig.update_xaxes(title='Maturity', tickformat=".0f")
# fig.update_layout(title='Yield Curve')
fig.show()


In [163]:
# Pull recession data
rec = pdr("USREC", "fred", start="1935-12-01")
starts = rec[(rec.USREC==1) & (rec.USREC.shift()==0)]
ends   = rec[(rec.USREC==1) & (rec.USREC.shift(-1)==0)]
dates = pd.merge(starts.reset_index()['DATE'], ends.reset_index()['DATE'],left_index=True,right_index=True )
dates.columns=['start','end']
dates.start =dates.start.dt.to_period('M')
dates.end   =dates.end.dt.to_period('M')

In [164]:
# Create list of dictionaries for shading
def dict_creator(start,end):
    d = dict(
            type="rect",
            xref="x",
            yref="paper",
            x0=str(start),
            y0=0,
            x1=str(end),
            y1=1,
            fillcolor="DarkGray",
            opacity=0.5,
            layer="below",
            line_width=0,
        )
    return d
dict_list = [dict_creator(dates.loc[i,'start'], dates.loc[i,'end']) for i in dates.index]

In [165]:
fig = go.Figure()
series_to_plot = ['DGS3MO','DGS1','DGS10']

trace1= go.Scatter(x=df.index.astype(str), y=df['DGS1'], mode="lines", name='1-yr Treasury',
                hovertemplate="1-yr Treasury<br>%{x}: %{y:.1f}%<extra></extra>")
fig.add_trace(trace1)

trace10= go.Scatter(x=df.index.astype(str), y=df['DGS10'], mode="lines", name='10-yr Treasury',
                hovertemplate="10-yr Treasury<br>%{x}: %{y:.1f}%<extra></extra>")
fig.add_trace(trace10)

fig.update_yaxes(title='Yield (%)',tickformat=".0f")
fig.update_xaxes(title='Date')
fig.update_layout(xaxis_range=[str(min(df.index)),str(max(df.index))])
fig.update_layout(legend=dict(yanchor="top", y =0.99, xanchor="left", x=0.6))
# add nber recession indicators
fig.update_layout(shapes=dict_list)
fig.show()

## Bootstrapping

In [172]:
import numpy as np
import pandas as pd
A = [97.5, 0, 0.5, 100]
B = [95, 0, 1.0, 100]
C = [955, 0.025, 1.5, 1000]
D = [1000, 0.0575, 2.0, 1000]

bonds = np.row_stack((A, B, C, D))

In [173]:
df = pd.DataFrame(bonds, 
        columns = ['price', 'coupon_rate', 'maturity','face'], 
        index=['A','B','C','D'])
df['period'] = df.maturity*2
df

price  coupon_rate  maturity    face  period
A    97.5       0.0000       0.5   100.0     1.0
B    95.0       0.0000       1.0   100.0     2.0
C   955.0       0.0250       1.5  1000.0     3.0
D  1000.0       0.0575       2.0  1000.0     4.0

In [174]:
df=df.reset_index()
df.index = df.index+1
df.columns = ['bond', 'price', 'coupon_rate', 'maturity','face', 'period']
df

bond   price  coupon_rate  maturity    face  period
1    A    97.5       0.0000       0.5   100.0     1.0
2    B    95.0       0.0000       1.0   100.0     2.0
3    C   955.0       0.0250       1.5  1000.0     3.0
4    D  1000.0       0.0575       2.0  1000.0     4.0

In [175]:
# Find z1 

spot_rates = []
nop = 2
t = 1
p      = df.loc[t,'price']
face   = df.loc[t,'face']
cr     = df.loc[t,'coupon_rate']
period = df.loc[t,'period']
coupon = face*cr/nop
cf_maturity = face + coupon

z1 = (cf_maturity / p )**(1/period) - 1
spot_rates.append(z1)
z1


0.02564102564102555

In [176]:
# Find z2
t = 2
p      = df.loc[t,'price']
face   = df.loc[t,'face']
cr     = df.loc[t,'coupon_rate']
period = df.loc[t,'period']
coupon = face*cr/nop
cf_maturity = face + coupon

z2 = (cf_maturity / p )**(1/period) - 1
spot_rates.append(z2)
z2



0.025978352085153977

In [177]:
# Find z3 

t = 3
p      = df.loc[t,'price']
face   = df.loc[t,'face']
cr     = df.loc[t,'coupon_rate']
period = int(df.loc[t,'period'])
coupon = face*cr/nop
cf_maturity = face + coupon

pv_coupons = 0.0
for i in range(period-1):
    print(i)
    pv_coupons = pv_coupons + coupon / (1+spot_rates[i])**(i+1)
x = p - pv_coupons
z3 = (cf_maturity / x )**(1/period) - 1
spot_rates.append(z3)
z3



0
1


0.028390767355670476

In [178]:
# Find z4 
t = 4
p      = df.loc[t,'price']
face   = df.loc[t,'face']
cr     = df.loc[t,'coupon_rate']
period = int(df.loc[t,'period'])
coupon = face*cr/nop
cf_maturity = face + coupon

pv_coupons = 0.0
for i in range(period-1):
    print(i)
    pv_coupons = pv_coupons + coupon / (1+spot_rates[i])**(i+1)
x = p - pv_coupons
z4 = (cf_maturity / x )**(1/period) - 1
spot_rates.append(z4)
z4

0
1
2


0.02882263912764249

### Find new bond price

In [179]:
cfs = np.array([0,100,0,1100])
discount_factors = np.array([1/(1+spot_rates[i])**(i+1) for i in range(len(spot_rates))])
discount_factors

array([0.975     , 0.95      , 0.91944444, 0.89256109])

In [180]:
cfs @ discount_factors

1076.8171999459971

### Functions to generalize bootstrapping and pricing

In [181]:
def bootstrap(d, nop):
    ''' 
    d: a dataset with prices, face value, coupon_rate, period of maturity
    nop: compounding period (ie., 1 = annual, 2=semiannual)
    '''
    spot_rates = []
    for t in d.index:
        p      = d.loc[t,'price']
        face   = d.loc[t,'face']
        cr     = d.loc[t,'coupon_rate']
        period = int(d.loc[t,'period'])
        coupon = face*cr/nop
        cf_maturity = face + coupon

        pv_coupons = 0.0
        for i in range(period-1):
            pv_coupons = pv_coupons + coupon / (1+spot_rates[i])**(i+1)
        x = p - pv_coupons
        z = (cf_maturity / x )**(1/period) - 1
        spot_rates.append(z)
    return spot_rates
spot_curve = bootstrap(df,2)
spot_curve

[0.02564102564102555,
 0.025978352085153977,
 0.028390767355670476,
 0.02882263912764249]

In [182]:
def spot_pricer(cfs, spot):
    ''' 
    cfs:  list of cash flows at each period
    spot: list of spot rates at each period
    cfs should be the same length as spot
    '''
    cfs = np.array(cfs)
    discount_factors = np.array([1/(1+spot[i])**(i+1) for i in range(len(spot))])
    return cfs @ discount_factors
spot_pricer([0,100,0,1100], spot_curve)

1076.8171999459971

In [184]:
# Check that the prices are consistent with the spot curve

# pick a bond
BOND_ID = 'A'
bond_dict = {'A': 1, 'B':2, 'C':3, 'D':4}
def cf_generator(bond_id):
    i = bond_dict[bond_id]
    nop = 2
    face   = df.loc[i,'face']
    cr     = df.loc[i,'coupon_rate']
    period = int(df.loc[i,'period'])
    coupon = face*cr/nop
    cf_maturity = face + coupon
    cfs =  np.zeros(len(spot_curve))
    for i in range(period-1):
        cfs[i] = coupon
    cfs[period-1] = cf_maturity
    print('The bond cash flows for bond ' + bond_id + ' are: ', cfs)
    return cfs
cfs = cf_generator(BOND_ID)

p = spot_pricer(cfs.tolist(),spot_curve)
print('The fair price for ' + BOND_ID + f' is: ${p:,.2f}')


The bond cash flows for bond A are:  [100.   0.   0.   0.]
The fair price for A is: $97.50


### Arbitrage and replicating portfolio


Example #1 (2-period bond)

In [223]:
spot_pricer([15,115,0,0], spot_curve)

123.87500000000003

Example #2 (4-period bond)

In [205]:
# Target bond cash-flows
cfs = np.array([0,100,0,1100])
cfs

array([   0,  100,    0, 1100])

In [206]:

# matrix of cash flows for bonds A-D
CF = np.zeros((len(df), len(df)))
for j, id in enumerate(['A','B','C','D']):
    print(j)
    print(id)
    CF[j] = cf_generator(id)
CF

0
A
The bond cash flows for bond A are:  [100.   0.   0.   0.]
1
B
The bond cash flows for bond B are:  [  0. 100.   0.   0.]
2
C
The bond cash flows for bond C are:  [  12.5   12.5 1012.5    0. ]
3
D
The bond cash flows for bond D are:  [  28.75   28.75   28.75 1028.75]


array([[ 100.  ,    0.  ,    0.  ,    0.  ],
       [   0.  ,  100.  ,    0.  ,    0.  ],
       [  12.5 ,   12.5 , 1012.5 ,    0.  ],
       [  28.75,   28.75,   28.75, 1028.75]])

In [208]:
# Solve the system of equations
portfolio = cfs @ np.linalg.inv(CF)
portfolio

array([-0.3036167 ,  0.6963833 , -0.03036167,  1.06925881])

In [216]:
# Check that replicating portfolio delivers same cash flows
repl_cfs = portfolio @ CF 
repl_cfs.astype(int)

array([   0,  100,    0, 1100])

In [218]:
# Price of replicating portfolio
repl_price = portfolio @ df.price
repl_price

1076.8171999459971

In [225]:
profit = repl_price-1050
profit

26.817199945997118